name: OpenCommandBlock
version: ${project.version}
main: com.github.kisaragieffective.opencommandblock.OpenCommandBlock
softdepend:
  - WorldGuard

commands:
  cbgamemode:
    description: /gamemode
    aliases:
      - cbgm
    usage: "/<command> [mode;GAMEMODE]"
  cbtell:
    description: /tell @p some
    usage: "/<command> [message;STRING]"
  cbtell-a:
    description: /tell @a some
  cbtellraw:
    description: /tellraw @p some
  cbtellraw-a:
    description: /tellraw @a some
  cbtpt:
    description: /tpt arg1
  checkregion:
    description: Check the region.
    aliases:
      - chkrgon
  opencommandblock:
    description: The root command for utilities.
    usage: "/<command> <arguments...>"
    aliases:
      - ocb
      - opencb
  testselector:
    description: Test for the selector query.
    usage: "/<command>"


